const express = require("express");
const app = express();
var bodyParser = require("body-parser");
const path = require('path')
var nodemailer = require('nodemailer');


app.use(express.static('public'));
app.use(express.static('public/css'));
app.use(express.static(__dirname));

app.set('view engine', 'html');

app.use(bodyParser.json());
app.use(bodyParser.urlencoded());

app.get('/', function(request, response) {
  console.log('GET /')
  var html = `
    <html>
        <body>
            <form method="post" action="http://localhost:3000">Name: 
                <input type="text" name="name" />
                <input type="submit" value="Submit" />
            </form>
        </body>
    </html>`
  response.writeHead(200, {'Content-Type': 'text/html'})
  response.end(html)
})

app.post('/', function(request, response) {
  console.log('POST /')
  console.dir(request.body)
  response.writeHead(200, {'Content-Type': 'text/html'})
  let lineOne = "Thank you for your response, " + request.body.name + ".<br>";
  var output = lineOne;
  let lineTwo = "Your address is: " + request.body.address + ".<br>";
  output += lineTwo;
  let lineThree = "Your Phone number is: " + request.body.phone + ".<br>";
  output += lineThree;
  let lineFour = "Your Email is: " + request.body.email + ".<br>";
  output += lineFour;
  let lineFive = "Your comments given are: " + request.body.comments + ".<br>";
  output += lineFive;
  
  //start email
   const transporter = nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    auth: {
		//autogenerated username and password when created ethereal account
        user: 'jackson.nicolas41@ethereal.email',
		//hidden for screenshots
        pass: 'YNXYwZVHZ6wBD24vaU'
    }
  });
  let mailinfo = {
		from: 'jackson.nicolas41@ethereal.email',
		to: request.body.email,
		subject: 'Submission Confirmation',
		html: '<p>Dear ' + request.body.name + ',</p>' +
		'<p>Submission Review:</p>' +
		'<p>Address: ' + request.body.address + '</p>' +
		'<p>Phone Number: ' + request.body.phone + '</p>' +
		'<p>Email: ' + request.body.email + '</p>' +
		'<p>Comments: ' + request.body.comments + '</p>' +
		'<p>Thank you for your feedback submission.</p><p>Sincerely,</p><p>Tyler</p>'
	};
	
	transporter.sendMail(mailinfo, function (err, info){
		console.log(Object.assign({}, mailinfo));
		if(err){
			console.log('SEND ERROR');
			console.log(err);
		}
		else{
			console.log('MESSAGE SENT');
			console.log(info);
		}
	});
  //end email
  
  response.write(output);
  response.end('Thank you.')
})

port = 3000
app.listen(port)
console.log(`Listening at http://localhost:${port}`)
